name: Data Loader - IP Marketplace

on:
  workflow_dispatch:
    inputs:
      aws-account:
        type: choice
        description: 'AWS Account'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
      aws-region:
        type: choice
        description: 'AWS Region'
        required: true
        default: us-east-1
        options:
          - us-east-1

env:
  AWS_ACCOUNT: ${{ inputs.aws-account }}
  AWS_REGION: ${{ inputs.aws-region }}

permissions:
  id-token: write
  contents: read

jobs:
  data-loader-ip-marketplace:
    name: 'Data Loader - IP Marketplace'
    environment: data - ip-marketplace - ${{ inputs.aws-account}} - ${{ inputs.aws-region}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/portal-data-loaders
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Login to AWS
        id: login-to-aws
        uses: ./.github/actions/configure-aws
        with:
          aws-access-key-id: ${{ secrets.AWS_CORE_TERRAFORM_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CORE_TERRAFORM_SECRET_KEY }}
          aws-region: ${{ inputs.aws-region }}
          aws-account: ${{ inputs.aws-account }}

      - run: echo AWS_ACCOUNT=$AWS_ACCOUNT AWS_REGION=$AWS_REGION
      - run: python --version
      - run: pip install -r requirements.txt
      - run: python no_ip_for_you.py
