name: Platform Docs Cross Account

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Deploy Platform Docs'
        required: true
        default: 'manual'
      aws-account:
        type: choice
        description: 'AWS Account'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod

env:
  AWS_REGION: us-east-1
  HJ_API_KEY: ${{ secrets.HJ_API_KEY }}

permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: ${{ inputs.aws-account || 'dev' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to AWS
        id: login-to-aws
        uses: ./.github/actions/configure-aws
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-account: ${{ inputs.aws-account }}

      - run: pip install -r docs/requirements.txt
      - run: pip install --editable ./docs/redesignhealth-mkdocs/
      - run: python docs/scripts/concat-glossary.py docs/glossary docs/glossary.md
      - run: AWS_ACCOUNT=${{ inputs.aws-account}} mkdocs build

      #- run: cp -av dist/storybook site/storybook

      #- run: aws s3 sync site s3://dev-design.redesignhealth.com/ --delete
      #- run: aws cloudfront create-invalidation --distribution-id EDRRGJ4JZFYU6 --paths "/*"
