name: Km Docs Deployment (Cross Account)

on:
  workflow_dispatch:
    inputs:
      aws-account:
        type: choice
        description: 'AWS Account'
        required: true
        options:
          - prod
          - staging
          - dev
      aws-region:
        type: choice
        description: 'AWS Region'
        required: true
        options:
          - us-east-1
      app:
        type: choice
        default: km-docs-lambda
        options:
          - km-docs-lambda
      lambda-name:
        type: choice
        default: km-docs
        options:
          - km-docs

env:
  ECR_REPOSITORY: ${{inputs.aws-account}}-${{inputs.app}}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: ${{ inputs.aws-account || 'dev' }}
    defaults:
      run:
        working-directory: apps/${{ inputs.app }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - uses: actions/checkout@v3    
      - name: Login to AWS
        id: login-to-aws
        uses: ./.github/actions/configure-aws
        with:
          aws-region: ${{ inputs.aws-region }}
          aws-account: ${{ inputs.aws-account }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --platform=linux/arm64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Update Lambda and Publish
        run: |
          aws lambda update-function-code --function-name ${{ inputs.lambda-name }} --image-uri ${{ steps.build-image.outputs.image }} --publish
