cockroach:
  host: free-tier14.aws-us-east-1.cockroachlabs.cloud
  db: staging_company_api
  cluster: staging-plat-ds-11727
  ## Folder location is the same locally and in Docker image
  sslRootCert: ./certs/staging-plat-ds.crt

spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://${cockroach.host}:26257/${cockroach.db}?sslmode=verify-full&sslrootcert=${cockroach.sslRootCert}&options=--cluster=${cockroach.cluster}
    username: opco-service
    # password supplied through secret manager

aws:
  enabled: true
  secret:
    name: staging/company-api
  sqs:
    jiraIssueQueue: https://sqs.us-east-1.amazonaws.com/262075340325/jirawebhook.fifo
  search:
    service: es
  s3:
    assets:
      bucket: rh-staging-company-api-assets
      url: https://company-api-assets.staging.redesignhealth.com

jira:
  enabled: true
  username: jiraplatformservice@redesignhealth.com
  request:
    user:
      project: 10106 # DP (DevOps Platform)
    infrastructure:
      project: 10106 # DP (DevOps Platform)

search:
  hostname: vpc-search-utttyuh6ntqjn5nr4nwfcsc2bq.us-east-1.es.amazonaws.com

notification:
  portal:
    hostname: https://platform.staging.redesignhealth.com
  advise:
    hostname: https://third-party-network.staging.redesignhealth.com

google-drive-lambda:
  hostname: https://2b636bbrcpkei4zp7tbq32hede0obyyq.lambda-url.us-east-1.on.aws/
mkdocs-lambda:
  hostname: https://2b636bbrcpkei4zp7tbq32hede0obyyq.lambda-url.us-east-1.on.aws/

prometheus-service:
  instance: company-api.staging.redesignhealth.com:80

