spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:26257/defaultdb
    username: root
    password:
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,env

aws:
  secret:
    name: dev/company-api

prometheus-service:
  base-url: https://www.example.com
